import type { PlanInfo } from "../types";

export const PLAN_CATALOG: PlanInfo[] = [
  {
    key: "gratis",
    nombre: "Gratis",
    precio: "$0",
    subtitle: "Para empezar sin costo y ordenar el inventario básico.",
    products: "Hasta 10 productos",
    limite_productos: 10,
    precio_mensual: 0,
    accent: "var(--success)",
    destacado: false,
    soporte: {
      nivel: "Estándar",
      tiempo: "Respuesta en 72 h hábiles",
      canal: ["Correo"],
      personalizado: false,
      prioridad: "Normal",
    },
    metas_ventas: false,
    reportes: ["Métricas básicas"],
    graficas: ["Resumen simple"],
    features: [
      "Control de stock esencial",
      "Alta y edición de productos",
      "Vista simple de métricas",
    ],
    limites: {
      productos: 10,
      usuarios: 1,
      historial_ventas: "30 días",
    },
  },
  {
    key: "premium",
    nombre: "Premium",
    precio: "$5099,99/mes",
    subtitle: "Más capacidad para crecer con datos más claros.",
    products: "Hasta 100 productos",
    limite_productos: 100,
    precio_mensual: 5099.99,
    accent: "var(--accent)",
    destacado: true,
    soporte: {
      nivel: "Prioritario",
      tiempo: "Respuesta en 24 h hábiles",
      canal: ["Correo", "WhatsApp"],
      personalizado: false,
      prioridad: "Alta",
    },
    metas_ventas: true,
    reportes: ["Métricas avanzadas", "Gráficas de ventas"],
    graficas: ["Torta por categoría", "Progreso de ventas", "Metas de ventas"],
    features: [
      "Más métricas y gráficos",
      "Seguimiento de stock bajo",
      "Metas de ventas mensuales",
      "Panel con análisis visual",
    ],
    limites: {
      productos: 100,
      usuarios: 1,
      historial_ventas: "Histórico completo",
    },
  },
  {
    key: "pro",
    nombre: "Pro",
    precio: "$9999,99/mes",
    subtitle: "Para operación completa, análisis y soporte más cercano.",
    products: "Productos ilimitados",
    limite_productos: null,
    precio_mensual: 9999.99,
    accent: "var(--warning)",
    destacado: false,
    soporte: {
      nivel: "VIP / Personalizado",
      tiempo: "Respuesta en 8 h hábiles",
      canal: ["Correo", "WhatsApp", "Teléfono"],
      personalizado: true,
      prioridad: "Máxima",
    },
    metas_ventas: true,
    reportes: ["Reportes de ventas", "Gráficos de análisis", "Análisis avanzado"],
    graficas: ["Torta por categoría", "Progreso de ventas", "Metas de ventas", "Análisis histórico"],
    features: [
      "Reportes de ventas",
      "Gráficos de análisis",
      "Metas de ventas avanzadas",
      "Soporte personalizado",
      "Inventario compartido (hasta 5 personas)",
      "Reporte PDF por período",
    ],
    limites: {
      productos: null,
      usuarios: 1,
      historial_ventas: "Histórico completo",
      inventario_compartido: 5,
      reporte_pdf: true,
    },
  },
];
